### ISSUE TITLE
Map not working after Update from V1.0

### ISSUE THREAD

**Issue by octaviogamero27** [dotswan/filament-map-picker#23]
![imagen](https://github.com/dotswan/filament-map-picker/assets/43446223/c832b65d-04be-4d94-9465-e3a80ffe20ca)

The map in form is not displayed.
It does not obtain the location in real time, and it does not load the map

Please Help Thanks

**Comment by mohaphez** [comment]
Hi @octaviogamero27 

Can you share your code ?
Are you see any error inside console.log ?
Are you use spa mode ?

If you answer these questions, I can help you better

**Comment by mohaphez** [comment]
I rewrote your code exactly in my project. But the map loads correctly. 
I even put it in a filament repeater and everything was fine again. 

Did this happen to you after the package update?

You can enter the following commands and test again.

```
php artisan optimize:clear
php artisan cache:clear
php artisan filament:assets
```

**Comment by mohaphez** [comment]
Ok, I found that your code works and displays correctly with the repeater for create.

But I encountered a problem in the edit mode. 

And the reason is that I did not have a one-to-many relationship for the location and the primary variables were not correctly referenced to the field. 

Can you test the field outside the repeater or put it in another resource?

 For use with repeaters, make sure the values ​​are correctly referenced in the map field.

**Comment by mohaphez** [comment]
I really have no idea anymore for now, 

Can you downgrade the package to version 1.2.2 and test it ?

**Comment by mohaphez** [comment]
It is strange . 

The difference between these two versions is that from version 1.1.1 onwards, apline.js is used instead of raw JavaScript (window.mapPicker). 

I will definitely look into this. 

Just are you sure you don't have any errors in the console, yes ?

And one more question, do you install and use any other package or library related to leaflet or map in your project other than this package?

**Comment by mohaphez** [comment]
Hello @octaviogamero27 ,

Can you please update your package to version 1.2.5 and confirm that the issue has been resolved?
