### ISSUE TITLE
Unable to Update Latitude and Longitude TextInputs When Marker is Selected Without Live Location

### ISSUE THREAD

**Issue by ridwannurjaman** [dotswan/filament-map-picker#56]
When using the Map component, I encountered an issue where the TextInput fields for latitude and longitude do not update when a marker is selected, and the liveLocation option is disabled.

Issue Details:

- Working Scenario: With liveLocation enabled, the TextInput fields (lat and long) update correctly based on location changes.
- Problematic Scenario: When liveLocation is disabled, selecting a marker on the map does not update the TextInput fields for latitude and longitude.

Code
```
TextInput::make('lat')
                        ->reactive()
                        ->required(),
                    TextInput::make('long')
                        ->reactive()
                        ->required(),
                    Map::make('location')
                        ->label('Location')
                        // ->liveLocation(true, true, 5000)
                        ->columnSpanFull()
                        ->afterStateUpdated(function (Set $set, ?array $state): void {
                            $set('lat',  $state['lat']);
                            $set('long', $state['lng']);
                        })
                        ->afterStateHydrated(function ($state, $record, Set $set): void {
                            $set('location', ['lat' => $record?->lat, 'lng' => $record?->long]);
                        })
                        ->extraStyles([
                            'min-height: 30vh',
                        ])
                        ->defaultLocation(latitude: 40.4168, longitude: -3.7038)
                        ->showMarker(true)
                        ->clickable(true)
                        ->tilesUrl("https://tile.openstreetmap.de/{z}/{x}/{y}.png")
                        ->zoom(12)
```

I would appreciate guidance on how to make sure the TextInput fields for latitude and longitude are updated correctly based on the marker's location, regardless of whether liveLocation is enabled or disabled.

Thank you!

**Comment by mohaphez** [comment]
Hello @ridwannurjaman,  

You should not disable the `liveLocation` option. When this option is disabled, no updates are sent from the frontend to the backend after changes are made to the component, preventing the desired fields from being populated.  

Please note that the `liveLocation` option has two main functionalities:  

1. **Usage Example:**  
   ```  
     ->liveLocation(true)  
   ```  
   This means that after the marker is moved, the latest changes are sent to the backend, triggering the `afterStateUpdated` function.  

2. **Usage Example:**  
   ```  
     ->liveLocation(true, true, 5000)  
   ```  
   In addition to the first functionality, this enables an interval-based feature that retrieves the user's latest location from the browser and automatically updates the marker and other fields in real time.  

If you have any questions or face other issues, please feel free to share them with us. We’d be happy to help!

**Comment by binsarjr** [comment]
<img width="519" alt="Screenshot 2024-12-02 at 03 39 29" src="https://github.com/user-attachments/assets/fee40128-aef1-4959-8474-a982b4e64db0">

I tried to track one by one where the problem was, the problem was, when editing and showMarker and clickable were activated. which will run the function `setCoordinates -> updateMarker -> updateLocation`

Here the coordinates have been set and saved to the latest state by running the `setCoordinates` function

but the problem is every time this `setCoordinates` is executed, also call `updateLocation` which apparently `updateLocation` will also update the coordinates with the center point


see `setCoordinates` always call `updateMarker`

https://github.com/dotswan/filament-map-picker/blob/285158a99a09f3dc92c87fdf1bf5231e4396575a/resources/js/index.js#L278-L291

and `updateMarker` also call `updateLocation` when showMarker is true, this function will take the coordinates of the center point of the map

https://github.com/dotswan/filament-map-picker/blob/285158a99a09f3dc92c87fdf1bf5231e4396575a/resources/js/index.js#L365-L371

so that every time the map picker moves, the coordinates will always return to the center point


this is function `updateLocation`:
https://github.com/dotswan/filament-map-picker/blob/285158a99a09f3dc92c87fdf1bf5231e4396575a/resources/js/index.js#L233-L248
